#!/usr/bin/env node
// Builds console/data.js - the Shift Console's data - from the timesheet CSVs.
//
// The console is a local page (console/index.html, opened straight from disk). A page
// on file:// may not read the CSVs beside it, but it may load a <script>, so the CSVs
// are compiled into `window.TIMESHEET_DATA = {...}` in console/data.js. The CSVs stay
// the only source of truth; data.js is a disposable, git-ignored derivative.
//
//   node tools/build_console_data.js           # rebuild now
//   require(...).buildIfStale(TIMESHEETS)       # used by the hooks: rebuild only when a CSV is newer
//
// Called from the timesheet-logging hooks (UserPromptSubmit and Stop), so it must be
// fast, silent, and never throw into the hook.

const fs = require('fs');
const path = require('path');

const HERE = path.resolve(__dirname, '..');   // Timesheets/

function parseCSVLine(line) {
  const fields = [];
  let cur = '', inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (inQuotes) {
      if (c === '"') { if (line[i + 1] === '"') { cur += '"'; i++; } else { inQuotes = false; } }
      else { cur += c; }
    } else if (c === '"') { inQuotes = true; }
    else if (c === ',') { fields.push(cur); cur = ''; }
    else { cur += c; }
  }
  fields.push(cur);
  return fields;
}

function readCSV(file) {
  const text = fs.readFileSync(file, 'utf8').replace(/^﻿/, '');
  const lines = text.split(/\r?\n/).filter(l => l.length > 0);
  if (!lines.length) return [];
  const header = parseCSVLine(lines[0]).map(h => h.trim());
  return lines.slice(1).map(l => {
    const f = parseCSVLine(l), o = {};
    header.forEach((h, i) => { o[h] = (f[i] || '').trim(); });
    return o;
  });
}

// A project CSV row. Some historical rows have an UNQUOTED comma inside `workstream`, so a
// row can carry more fields than the header. `workstream` is therefore everything from its
// column to the end, except a trailing `epic` field, which is only taken as an epic when it is
// a real key from _epics.csv; anything else is description text that spilled over.
function readTimesheet(file, epicKeys) {
  const text = fs.readFileSync(file, 'utf8').replace(/^﻿/, '');
  const lines = text.split(/\r?\n/).filter(l => l.length > 0);
  if (!lines.length) return [];
  const header = parseCSVLine(lines[0]).map(h => h.trim());
  const at = n => header.indexOf(n);
  const ws = at('workstream'), hasEpic = at('epic') !== -1;
  return lines.slice(1).map(l => {
    const f = parseCSVLine(l);
    let tail = f.slice(ws), epic = '';
    if (hasEpic && tail.length > 1) {
      const last = tail[tail.length - 1].trim();
      if (last === '' || epicKeys.has(last)) { epic = last; tail = tail.slice(0, -1); }
    }
    const g = n => (at(n) === -1 ? '' : (f[at(n)] || '').trim());
    return { id: g('id'), date: g('date'), start: g('start'), end: g('end'), status: g('status'),
             workstream: tail.join(',').trim(), epic };
  });
}

function sources(root) {
  const reg = path.join(root, '_projects.csv');
  const files = [reg, path.join(root, '_epics.csv')];
  if (fs.existsSync(reg)) readCSV(reg).forEach(p => p.file && files.push(path.join(root, p.file)));
  return files.filter(f => fs.existsSync(f));
}

function build(root) {
  root = root || HERE;
  const projects = readCSV(path.join(root, '_projects.csv')).map((p, i) => ({
    file: p.file, client: p.client, project: p.project,
    billable: (p.billable || '').toLowerCase() === 'true',
    colorLight: p.color_light || null, colorDark: p.color_dark || null, order: i
  }));
  const epicsFile = path.join(root, '_epics.csv');
  const epics = fs.existsSync(epicsFile)
    ? readCSV(epicsFile).map(e => ({ project: e.project, key: e.key, label: e.label, order: Number(e.order) || 99 }))
    : [];
  const epicKeys = new Set(epics.map(e => e.key));
  const rows = [];
  projects.forEach(p => {
    const f = path.join(root, p.file);
    if (!fs.existsSync(f)) return;
    readTimesheet(f, epicKeys).forEach(r => {
      if (!r.id || !r.date) return;
      rows.push(Object.assign({ project: p.project }, r));
    });
  });
  rows.sort((a, b) => (a.date + a.start).localeCompare(b.date + b.start));
  const data = { generatedAt: new Date().toISOString(), projects, epics, rows };
  const outDir = path.join(root, 'console');
  fs.mkdirSync(outDir, { recursive: true });
  const out = path.join(outDir, 'data.js');
  const tmp = out + '.tmp';
  // Written to a temp file first and renamed, so the page never loads a half-written file.
  fs.writeFileSync(tmp, '// GENERATED by tools/build_console_data.js from the timesheet CSVs. Do not edit.\n' +
                        'window.TIMESHEET_DATA = ' + JSON.stringify(data) + ';\n', 'utf8');
  fs.renameSync(tmp, out);
  return { out, rows: rows.length, projects: projects.length };
}

function buildIfStale(root) {
  try {
    root = root || HERE;
    const out = path.join(root, 'console', 'data.js');
    const built = fs.existsSync(out) ? fs.statSync(out).mtimeMs : 0;
    if (sources(root).some(f => fs.statSync(f).mtimeMs > built)) return build(root);
  } catch (e) { /* never break a hook */ }
  return null;
}

module.exports = { build, buildIfStale };

if (require.main === module) {
  if (process.argv.includes('--if-stale')) {
    // Stop-hook mode: silent, only inside this workspace, rebuild only when a CSV changed.
    const workspace = path.resolve(HERE, '..').toLowerCase();
    if (process.cwd().toLowerCase().startsWith(workspace)) buildIfStale(HERE);
  } else {
    const r = build(HERE);
    console.log('wrote ' + r.out + ': ' + r.rows + ' rows, ' + r.projects + ' projects');
  }
}
